### ISSUE TITLE
Bakery Update

### ISSUE THREAD

**Issue by BrownieZoulou** [clement-or/space-station-14#7]
# Introduction
Afin de diversifier le travail du cuisinier et ajouter une nouvelle perspective de travail de la matière consommable, cette mise à jour va permettre de préparer une pâte avant de la mettre a cuir. La forme donnée à cette pâte permettra de donner de nouvelles pâtisseries.

Cette mise à jour suit toujours le système "hard-coded recipes" duquel le jeu souhaites s'éloigner à l'avenir mais je fais ce que je veux :p

De plus, cette mise à jour prend le soin de modifier quelques recettes existante afin de rendre le système plus cohérent.

# TODO

- [ ] Produire la liste de pâtisserie
- [ ] Modifier la pâte à gâteau "cake batter"
- Changer le nom pour "pastrie dough"
- Changer la recette du "cake"
- Rendre la pastrie dough slicable
- [ ] Mettre au point le pastrie dough slice (se référer à arborescence)
- Revoir l'arborescence du projet
- Permettre à la pastrie dough slice d'être cliquable, ce qui la fait changer de forme:
     - Ronde
     - Plate
     - Triangulaire
     - Rectangulaire
     - Roulée
- [ ] Créer les recettes
- [ ] Créer les prototype de nourritures
- [ ] Créer les sprites
- [ ] Manger
- [ ] ADDITIONNELLE Remplir le projet pièce montée

# Arborescence
- Food
- - Baked
- - - Pastrie.yml
> - Pastrie dough slice injectable
> - Round pastrie dough slice base
> then recipes...
> - Flat pastrie dough slice base
> then recipes...
> - Triangular pastrie dough slice base
> then recipes...
> - Rectangular pastrie dough slice base
> then recipes...
> - Rolled pastrie dough slice base
> then recipes...

# Recettes
### Rondes
- [ ] Chouquettes
- [ ] **Pièces montées** (se référer à projet pièce montée)
- [ ] Profiteroles
- [ ] Beignets
### Plates
- [ ] Cookies & ses variantes
- [ ] Bicuits
### Triangulaires
- [ ] Croissant
- [ ] Chausson au pommes
### Rectangulaire
- [ ] Chocopain
- [ ] Mille feuille
### Enroulée
- [ ] Eclair
- [ ] Pain au raisin

# Projet pièce montée
Le but pour la pièce montée est d'être un immense plats que les joueurs, lorsqu'il clique dessus, récupère une partie à manger. Le sprite de la pièce montée diminuerait à chaque part prise. Pour être déplacer, ce plat doit être drag pour l'instant. Peut êytre porté?

À l'avenir, ce genre de plat pourrait également permettre de produire des plateau apéritifs.

Appelons les les PECKABLE
